-- Q16) Display the customer ID, customer city, and order ID for each order.
SELECT c.customer_id , c.customer_city , o.order_id
FROM customers c 
JOIN orders o 
ON c.customer_id = o.customer_id;

-- Q17) Find the number of orders placed by each customer.
SELECT customer_id, COUNT(*) AS order_count
FROM orders
GROUP BY customer_id;

-- Q18) Find the number of orders placed by customers from each state.
SELECT c.customer_state, COUNT(*) AS order_count
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_state;

-- Q19) Find the top 10 states based on the number of orders.
SELECT c.customer_state,COUNT(*) AS order_count
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_state
ORDER BY order_count DESC
LIMIT 10;

-- Q20) Find customers who have placed more than 5 orders
SELECT c.customer_unique_id, COUNT(*) AS order_count
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
HAVING COUNT(*) > 5;

-- Q21) Find the customers whose number of orders is greater than the aveage number of orders per customer.(subquery)
SELECT customer_unique_id,COUNT(*) AS order_count
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY customer_unique_id
HAVING COUNT(*) > (SELECT AVG(order_count) 
                   FROM (
                     SELECT c2.customer_unique_id,
                            COUNT(*) AS order_count
					 FROM customers c2
                     JOIN orders o2
                     ON c2.customer_id = o2.customer_id
                     GROUP BY c2.customer_unique_id
				) AS customer_orders
);
                     
-- Q22) Find the product with the highest total sales revenue.
SELECT product_id, SUM(price) AS total_sales
FROM order_items
GROUP BY product_id
ORDER BY total_sales DESC
LIMIT 1;

-- Q23) Find the top 10 products based on total sales revenue.
SELECT product_id, SUM(price) AS total_sales
FROM order_items
GROUP BY product_id
ORDER BY total_sales DESC
LIMIT 10;

-- Q24) Find the total sales revenue generated by each product.
SELECT product_id, SUM(price) AS total_sales
FROM order_items
GROUP BY product_id;

-- Q25) Which payment methods generate the highest total payment value?
SELECT payment_type,
    SUM(payment_value) AS total_payment
FROM order_payments
GROUP BY payment_type
ORDER BY total_payment DESC;

-- Q26) Which product categories generate the highest revenue?
SELECT ct.product_category_name_english AS category,
    SUM(oi.price) AS total_revenue
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
JOIN category_translation ct
ON p.product_category_name = ct.product_category_name
GROUP BY ct.product_category_name_english
ORDER BY total_revenue DESC;

-- Q27) Which sellers generate the highest total revenue?
SELECT oi.seller_id,s.seller_city,s.seller_state,
    SUM(oi.price) AS total_revenue
FROM order_items oi
JOIN sellers s
ON oi.seller_id = s.seller_id
GROUP BY oi.seller_id,s.seller_city,s.seller_state
ORDER BY total_revenue DESC;

-- Q28) How does total revenue change month by month?
SELECT DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
    SUM(oi.price) AS total_revenue
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m')
ORDER BY month;

-- Q29) What percentage of orders were delivered late compared with the estimated delivery date?
SELECT
    ROUND(100.0 * SUM(
            CASE
                WHEN order_delivered_customer_date > order_estimated_delivery_date THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS late_delivery_percentage
FROM orders
WHERE order_delivered_customer_date IS NOT NULL;

-- Q30) What is the average review score for each order status?
SELECT o.order_status,
    ROUND(AVG(r.review_score), 2) AS avg_review_score
FROM orders o
JOIN order_reviews r
ON o.order_id = r.order_id
GROUP BY o.order_status
ORDER BY avg_review_score DESC;

-- Q31) Which product categories have the lowest average customer review scores?
SELECT p.product_category_name,
    ROUND(AVG(r.review_score), 2) AS avg_review_score
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
JOIN order_reviews r
ON oi.order_id = r.order_id
GROUP BY p.product_category_name
ORDER BY avg_review_score ASC;

-- Q32) Find customers who have placed orders on more than one different day.
SELECT c.customer_unique_id,
    COUNT(DISTINCT DATE(o.order_purchase_timestamp)) AS purchase_days
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
HAVING COUNT(DISTINCT DATE(o.order_purchase_timestamp)) > 1
ORDER BY purchase_days DESC;

-- Q33) Find sellers who have completed more than 100 orders.
SELECT oi.seller_id,
    COUNT(DISTINCT oi.order_id) AS total_orders
FROM order_items oi
JOIN orders o
ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY oi.seller_id
HAVING COUNT(DISTINCT oi.order_id) > 100
ORDER BY total_orders DESC;

-- Q34) Find the average delivery time in days for each customer state.
SELECT c.customer_state,
    ROUND(AVG(DATEDIFF(
                o.order_delivered_customer_date,
                o.order_purchase_timestamp
            )
        ), 2
    ) AS avg_delivery_days
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.order_delivered_customer_date IS NOT NULL
GROUP BY c.customer_state
ORDER BY avg_delivery_days ASC;

-- Q35) Rank sellers within each state based on their total revenue.
SELECT s.seller_id,
    s.seller_state,
    SUM(oi.price) AS total_revenue,
    RANK() OVER (
        PARTITION BY s.seller_state
        ORDER BY SUM(oi.price) DESC
    ) AS seller_rank
FROM sellers s
JOIN order_items oi
ON s.seller_id = oi.seller_id
GROUP BY s.seller_id,s.seller_state
ORDER BY s.seller_state, seller_rank;


SELECT customer_id,order_id,order_status
FROM orders
WHERE order_status = delivered;

SELECT DISTINCT customer_state
FROM customers;

SELECT product_id,price
FROM order_items
ORDER BY price DESC
LIMIT 10;

SELECT customer_state , COUNT(customer_id) AS customer_count
FROM Customers
GROUP BY customer_state;

SELECT payment_type , SUM(payment_value) AS total_payment
FROM order_payments
GROUP BY payment_type
ORDER BY total_payment DESC;

SELECT c.customer_unique_id , o.order_id, o.order_status
FROM customers c 
INNER JOIN orders o 
ON c.customer_id = o.customer_id;

SELECT c.customer_unique_id , COUNT(o.order_id) AS order_count
FROM customers c 
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY customer_unique_id
HAVING COUNT(o.order_id) > 5;

SELECT product_id , price
FROM order_items
WHERE price > (SELECT AVG(price) FROM order_items);


SELECT product_id , price,
   CASE
     WHEN price >= 500 THEN 'High'
     WHEN price <= 499 AND price >= 100 THEN 'medium'
     ELSE 'LOW'
     END AS price_category
FROM order_items;

SELECT s.seller_id , s.seller_state,
      SUM(oi.price) AS Total_revenue,
      RANK() OVER(PARTITION BY seller_state ORDER BY SUM(oi.price) DESC) AS rank_order
FROM sellers s
JOIN order_items oi
ON s.seller_id = oi.seller_id
GROUP BY seller_id,seller_state;
      
      

     

     



